Adding redux
kacpi52/learning_r pull request #3
Opened 2023-03-31 09:47 UTC by kacpi52

using redux and react-redux

2023-03-31 09:50 UTC, kacpi52 commented on src/Components/SidebarMenu/DropDown.jsx
tu dodalem tylko jeden link do dropdownu ale przeformatowal mi prettier i dlatego sie swieci caly , takze tego nie sprawdzaj

2023-04-13 20:43 UTC, wbluecloud requested changes
musisz poprawić strukturę katalogów 
+ kilka zmian

2023-04-13 20:43 UTC, wbluecloud commented on src/Lib/globalState/actions/dataActionTypes.js
> +};
👍

2023-04-13 20:43 UTC, wbluecloud commented on src/Lib/globalState/actions/dataActionCreators.js
> +  payload: dataSource,
nieoczywista zmienna - po czym ma szukac?

2023-04-13 20:43 UTC, wbluecloud commented on src/Lib/globalState/actions/dataActionCreators.js
> +});
👍

2023-05-18 21:43 UTC, wbluecloud reviewed
dorzuć update

2023-05-18 21:43 UTC, wbluecloud commented on src/Components/TopList/TopListLayout.jsx
>      }
co to robi?

2023-05-18 21:43 UTC, wbluecloud commented on src/Lib/store/reducers/combinedReducers.js
> +export default combinedReducers;
👍

2023-05-22 10:43 UTC, merged